# Generated by Django 5.1.2 on 2024-11-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('countryCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parentUuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(to='client.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receptionDate', models.DateTimeField()),
                ('expirationDate', models.DateTimeField(null=True)),
                ('productUuid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.productmodel')),
                ('supplierUuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.suppliermodel')),
                ('unitUuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.unitmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirationDate', models.DateTimeField(null=True)),
                ('currencyUuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.currencymodel')),
                ('stockUuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.stockmodel')),
            ],
        ),
    ]
