# Generated by Django 5.1.2 on 2024-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_following_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
