# Generated by Django 5.1.2 on 2024-11-07 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
    ]
