# Generated by Django 4.2.16 on 2024-12-14 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_offermodel_expiration_date_offerviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerviewmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
