# Generated by Django 4.2.16 on 2024-12-14 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_offerviewmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerviewmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='offerviewmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
