# Generated by Django 5.1.2 on 2024-12-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_orderoffermodel_discount_orderoffermodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='is_following_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
