# Generated by Django 5.1.2 on 2024-11-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_categorymodel_uuid_alter_currencymodel_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parentUuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.categorymodel'),
        ),
    ]
