# Generated by Django 4.2.16 on 2024-12-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_adresslineone_profilemodel_addresslineone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='stockUuid',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='productUuid',
            field=models.ForeignKey(default='2c711e1a-8c51-46ab-89e5-ddd46097d394', on_delete=django.db.models.deletion.PROTECT, to='client.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='emailConfirmationUuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='isEmailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
