# Generated by Django 5.1.2 on 2024-12-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_profilemodel_is_following_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
