# Generated by Django 4.2.16 on 2024-12-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('client', '0004_remove_offermodel_stockuuid_offermodel_productuuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymodel',
            name='countryCode',
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
    ]
