# Generated by Django 4.2.16 on 2024-12-14 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_offerviewmodel_date_offerviewmodel_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
