# Generated by Django 4.2.16 on 2024-12-15 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_promotionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='category',
            field=models.ForeignKey(default='fff087a8-5663-40f0-9e76-0ce472b95cba', on_delete=django.db.models.deletion.PROTECT, to='client.categorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionmodel',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
