# Generated by Django 5.1.2 on 2024-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_categorymodel_parentuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='countryCode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
