# Generated by Django 5.1.2 on 2024-12-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_profilemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'permissions': [('can_change_user_email', 'Can change email'), ('can_change_user_username', 'Can change username'), ('can_change_user_is_email_confirmed', 'Can change is_email_confirmed'), ('can_change_user_is_blocked', 'Can change is_blocked'), ('can_change_user_first_name', 'Can change first_name'), ('can_change_user_last_name', 'Can change last_name'), ('can_change_user_date_of_birth', 'Can change date_of_birth'), ('can_change_user_phone_number', 'Can change phone_number'), ('can_change_user_country', 'Can change country'), ('can_change_user_city', 'Can change city'), ('can_change_user_address_line_one', 'Can change address_line_one'), ('can_change_user_address_line_two', 'Can change address_line_two'), ('can_change_user_is_active', 'Can change is_active'), ('can_change_user_is_staff', 'Can change is_staff'), ('can_change_user_is_superuser', 'Can change is_superuser'), ('can_change_user_groups', 'Can change groups'), ('can_change_user_user_permissions', 'Can change user_permissions'), ('can_change_user_last_login', 'Can change last_login'), ('can_change_user_date_joined', 'Can change date_joined')]},
        ),
    ]
