# Generated by Django 4.2.16 on 2024-12-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_offermodel_discount_promotionmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionmodel',
            name='subject',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
