# Generated by Django 4.2.16 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_promotionmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
