# Generated by Django 5.1.2 on 2024-12-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_profilemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'permissions': [('change_user_email', 'Can change user email'), ('change_user_username', 'Can change user username'), ('change_user_is_email_confirmed', 'Can change user is_email_confirmed'), ('change_user_is_blocked', 'Can change user is_blocked'), ('change_user_first_name', 'Can change user first_name'), ('change_user_last_name', 'Can change user last_name'), ('change_user_date_of_birth', 'Can change user date_of_birth'), ('change_user_phone_number', 'Can change user phone_number'), ('change_user_country', 'Can change user country'), ('change_user_city', 'Can change user city'), ('change_user_address_line_one', 'Can change user address_line_one'), ('change_user_address_line_two', 'Can change user address_line_two'), ('change_user_is_active', 'Can change user is_active'), ('change_user_is_staff', 'Can change user is_staff'), ('change_user_is_superuser', 'Can change user is_superuser'), ('change_user_groups', 'Can change user groups'), ('change_user_user_permissions', 'Can change user user_permissions'), ('change_user_last_login', 'Can change user last_login'), ('change_user_date_joined', 'Can change user date_joined')]},
        ),
    ]
