# Generated by Django 5.1.2 on 2024-12-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_profilemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='unit',
        ),
    ]
