# Generated by Django 5.1.2 on 2024-12-31 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_stockmodel_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='client.currencymodel')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='client.currencymodel')),
            ],
        ),
    ]
