# Generated by Django 5.1.2 on 2025-01-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_currencyconversionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='invoice',
            field=models.FileField(default='', upload_to='invoices'),
            preserve_default=False,
        ),
    ]
