# Generated by Django 5.1.2 on 2025-01-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_ordermodel_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoffermodel',
            name='discount',
        ),
        migrations.AddField(
            model_name='orderoffermodel',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='client.currencymodel'),
            preserve_default=False,
        ),
    ]
