# Generated by Django 5.1.2 on 2025-01-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_orderoffermodel_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='contact',
            new_name='phoneNumber',
        ),
    ]
