# Generated by Django 5.1.2 on 2025-01-02 09:32

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_rename_contact_ordermodel_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
    ]
