# Generated by Django 5.1.2 on 2025-01-02 11:04

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_ordermodel_phonenumber_ordermodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='invoice',
            field=models.FilePathField(blank=True, null=True, path=pathlib.PurePosixPath('/Users/Work/Documents/dev/DAW/media/pdf')),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Confirmed'), (3, 'Delivering'), (4, 'Received'), (5, 'Completed'), (6, 'Cancelled')], default=0),
        ),
    ]
