# Generated by Django 5.1.2 on 2025-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_ordermodel_invoice_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
