# Generated by Django 5.1.2 on 2025-01-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_ordermodel_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='offers',
        ),
    ]
