# Generated by Django 5.1.2 on 2025-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_orderoffermodel_currency_ordermodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
